name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', 'pypy-3.7']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ matrix.python-version }}-pip-${{ hashFiles('setup.py') }}-${{ hashFiles('*-requirements.txt') }}
        restore-keys: ${{ runner.os }}-python-${{ matrix.python-version }}-pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install libmemcached-dev
    - name: Lint
      if: matrix.python-version == '3.10'
      run: |
        pip install -r lint-requirements.txt
        python setup.py check --restructuredtext --strict
        flake8
        black --check .
    - name: Disable IPv6 localhost
      run: |
        sudo sed -i '/::1/d' /etc/hosts
    - name: Tests
      run: |
        pip install -r test-requirements.txt
        pytest pymemcache/test/ \
            -m 'unit or integration' \
            --port ${{ job.services.memcached.ports[11211] }} \
            --tls-port ${{ job.services.tls_memcached.ports[11211] }}

    services:
      memcached:
        image: memcached:latest
        ports:
        - 11211/tcp
      tls_memcached:
        image: scoriacorp/tls_memcached:latest
        ports:
        - 11211/tcp
